//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MT.Data.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string bKepChi_Co {
            get {
                return ResourceManager.GetString("bKepChi_Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string bKepChi_Khong {
            get {
                return ResourceManager.GetString("bKepChi_Khong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string iDonViThoiGianBaoHanh_Nam {
            get {
                return ResourceManager.GetString("iDonViThoiGianBaoHanh_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string iDonViThoiGianBaoHanh_Ngay {
            get {
                return ResourceManager.GetString("iDonViThoiGianBaoHanh_Ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý.
        /// </summary>
        public static string iDonViThoiGianBaoHanh_Quy {
            get {
                return ResourceManager.GetString("iDonViThoiGianBaoHanh_Quy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string iDonViThoiGianBaoHanh_Thang {
            get {
                return ResourceManager.GetString("iDonViThoiGianBaoHanh_Thang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string iDonViThoiGianHieuLuc_Nam {
            get {
                return ResourceManager.GetString("iDonViThoiGianHieuLuc_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string iDonViThoiGianHieuLuc_Ngay {
            get {
                return ResourceManager.GetString("iDonViThoiGianHieuLuc_Ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý.
        /// </summary>
        public static string iDonViThoiGianHieuLuc_Quy {
            get {
                return ResourceManager.GetString("iDonViThoiGianHieuLuc_Quy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string iDonViThoiGianHieuLuc_Thang {
            get {
                return ResourceManager.GetString("iDonViThoiGianHieuLuc_Thang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBMM-Nguồn CT.
        /// </summary>
        public static string iLoaiKH_ct {
            get {
                return ResourceManager.GetString("iLoaiKH_ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string iLoaiKH_khac {
            get {
                return ResourceManager.GetString("iLoaiKH_khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Liệu KTMM.
        /// </summary>
        public static string iLoaiKH_tlmm {
            get {
                return ResourceManager.GetString("iLoaiKH_tlmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBMM-Nguồn TX.
        /// </summary>
        public static string iLoaiKH_tx {
            get {
                return ResourceManager.GetString("iLoaiKH_tx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về bảo hành.
        /// </summary>
        public static string iLoaiNhapBaoHanh_NhapBH {
            get {
                return ResourceManager.GetString("iLoaiNhapBaoHanh_NhapBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sau bảo hành.
        /// </summary>
        public static string iLoaiNhapBaoHanh_NhapNhanVeSauBH {
            get {
                return ResourceManager.GetString("iLoaiNhapBaoHanh_NhapNhanVeSauBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sau sửa chữa.
        /// </summary>
        public static string iLoaiNhapSuaChua_NhapSCNhanVeSauSC {
            get {
                return ResourceManager.GetString("iLoaiNhapSuaChua_NhapSCNhanVeSauSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sửa chữa.
        /// </summary>
        public static string iLoaiNhapSuaChua_NhapVaoSC {
            get {
                return ResourceManager.GetString("iLoaiNhapSuaChua_NhapVaoSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư đầu kỳ.
        /// </summary>
        public static string iLoaiPhieu_DauKy {
            get {
                return ResourceManager.GetString("iLoaiPhieu_DauKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về bảo hành.
        /// </summary>
        public static string iLoaiPhieu_NhapBH {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập mới.
        /// </summary>
        public static string iLoaiPhieu_NhapMoi {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập mượn.
        /// </summary>
        public static string iLoaiPhieu_NhapMuon {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapMuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập về sau mượn.
        /// </summary>
        public static string iLoaiPhieu_NhapNhanVe {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapNhanVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập về sau bảo hành.
        /// </summary>
        public static string iLoaiPhieu_NhapNhanVeSauBH {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapNhanVeSauBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập vào sau cài đặt.
        /// </summary>
        public static string iLoaiPhieu_NhapNhanVeSauCĐ {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapNhanVeSauCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập về sau sửa chữa.
        /// </summary>
        public static string iLoaiPhieu_NhapSCNhanVeSauSC {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapSCNhanVeSauSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập.
        /// </summary>
        public static string iLoaiPhieu_NhapSP {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập vào thu hồi.
        /// </summary>
        public static string iLoaiPhieu_NhapThuHoi {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapThuHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập vào cài đặt.
        /// </summary>
        public static string iLoaiPhieu_NhapVaoCĐ {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapVaoCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập vào sửa chữa.
        /// </summary>
        public static string iLoaiPhieu_NhapVaoSC {
            get {
                return ResourceManager.GetString("iLoaiPhieu_NhapVaoSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất đi bảo hành.
        /// </summary>
        public static string iLoaiPhieu_XuatBH {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất đi cài đặt.
        /// </summary>
        public static string iLoaiPhieu_XuatĐiCĐ {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatĐiCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất tiêu hủy.
        /// </summary>
        public static string iLoaiPhieu_XuatHuy {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất cho mượn.
        /// </summary>
        public static string iLoaiPhieu_XuatMuon {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatMuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất đi sửa chữa.
        /// </summary>
        public static string iLoaiPhieu_XuatSCĐi {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatSCĐi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất trả về sau sửa chữa.
        /// </summary>
        public static string iLoaiPhieu_XuatSCTraVeSauSC {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatSCTraVeSauSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất.
        /// </summary>
        public static string iLoaiPhieu_XuatSP {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất thu hồi.
        /// </summary>
        public static string iLoaiPhieu_XuatThuHoi {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatThuHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất trả về sau mượn.
        /// </summary>
        public static string iLoaiPhieu_XuatTra {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatTra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất trả về sau bảo hành.
        /// </summary>
        public static string iLoaiPhieu_XuatTraSauBH {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatTraSauBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu xuất trả về sau cài đặt.
        /// </summary>
        public static string iLoaiPhieu_XuatTraSauCĐ {
            get {
                return ResourceManager.GetString("iLoaiPhieu_XuatTraSauCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất đi bảo hành.
        /// </summary>
        public static string iLoaiXuatBaoHanh_XuatBH {
            get {
                return ResourceManager.GetString("iLoaiXuatBaoHanh_XuatBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất trả về sau bảo hành.
        /// </summary>
        public static string iLoaiXuatBaoHanh_XuatTraSauBH {
            get {
                return ResourceManager.GetString("iLoaiXuatBaoHanh_XuatTraSauBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất đi sửa chữa.
        /// </summary>
        public static string iLoaiXuatSuaChua_XuatSCĐi {
            get {
                return ResourceManager.GetString("iLoaiXuatSuaChua_XuatSCĐi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất trả về sau sửa chữa.
        /// </summary>
        public static string iLoaiXuatSuaChua_XuatSCTraVeSauSC {
            get {
                return ResourceManager.GetString("iLoaiXuatSuaChua_XuatSCTraVeSauSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục chứng thư số.
        /// </summary>
        public static string ImportDataType_DM_ChungThuSo {
            get {
                return ResourceManager.GetString("ImportDataType_DM_ChungThuSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string ImportDataType_DM_SanPham {
            get {
                return ResourceManager.GetString("ImportDataType_DM_SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tham số mật mã.
        /// </summary>
        public static string ImportDataType_DM_ThamSoMatMa {
            get {
                return ResourceManager.GetString("ImportDataType_DM_ThamSoMatMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn đầu kỳ.
        /// </summary>
        public static string ImportDataType_SoKho {
            get {
                return ResourceManager.GetString("ImportDataType_SoKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập về kho.
        /// </summary>
        public static string iNhapVeKho_LuuKho {
            get {
                return ResourceManager.GetString("iNhapVeKho_LuuKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập sử dụng.
        /// </summary>
        public static string iNhapVeKho_Sudung {
            get {
                return ResourceManager.GetString("iNhapVeKho_Sudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sử dụng.
        /// </summary>
        public static string iTCNhap_NhapMuon {
            get {
                return ResourceManager.GetString("iTCNhap_NhapMuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sau khi cho mượn.
        /// </summary>
        public static string iTCNhap_NhapTra {
            get {
                return ResourceManager.GetString("iTCNhap_NhapTra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về cài đặt.
        /// </summary>
        public static string iTCNhapCĐ_NhapCĐ {
            get {
                return ResourceManager.GetString("iTCNhapCĐ_NhapCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nhận về sau cài đặt.
        /// </summary>
        public static string iTCNhapCĐ_NhapLaiSauCĐ {
            get {
                return ResourceManager.GetString("iTCNhapCĐ_NhapLaiSauCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thu hồi.
        /// </summary>
        public static string iTCNhapTH_NhapThuHoi {
            get {
                return ResourceManager.GetString("iTCNhapTH_NhapThuHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất cho mượn.
        /// </summary>
        public static string iTCXuat_XuatMuon {
            get {
                return ResourceManager.GetString("iTCXuat_XuatMuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất trả sản phẩm.
        /// </summary>
        public static string iTCXuat_XuatTra {
            get {
                return ResourceManager.GetString("iTCXuat_XuatTra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất đi cài đặt.
        /// </summary>
        public static string iTCXuatCĐ_XuatCĐĐi {
            get {
                return ResourceManager.GetString("iTCXuatCĐ_XuatCĐĐi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất trả về sau cài đặt.
        /// </summary>
        public static string iTCXuatCĐ_XuatCĐTraVeSauCĐ {
            get {
                return ResourceManager.GetString("iTCXuatCĐ_XuatCĐTraVeSauCĐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất tiêu hủy.
        /// </summary>
        public static string iTCXuatTH_XuatHuy {
            get {
                return ResourceManager.GetString("iTCXuatTH_XuatHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất thu hồi.
        /// </summary>
        public static string iTCXuatTH_XuatThuHoi {
            get {
                return ResourceManager.GetString("iTCXuatTH_XuatThuHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHCĐSP_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHCĐSP_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHCĐSP_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHCĐSP_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHCĐSP_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHCĐSP_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHNM_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHNM_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHNM_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHNM_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetKHNM_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetKHNM_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNBH_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNBH_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNBH_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNBH_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNBH_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNBH_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNM_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNM_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNM_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNM_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNM_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNM_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNSC_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNSC_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNSC_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNSC_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPNSC_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPNSC_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXBH_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXBH_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXBH_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXBH_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXBH_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXBH_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXCĐSP_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXCĐSP_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXCĐSP_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXCĐSP_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXCĐSP_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXCĐSP_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXSC_ChoDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXSC_ChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXSC_DongYDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXSC_DongYDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt.
        /// </summary>
        public static string iTrangThaiDuyetPXSC_TuChoiDuyet {
            get {
                return ResourceManager.GetString("iTrangThaiDuyetPXSC_TuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHCDSP_ChuaThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHCDSP_ChuaThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string iTrangThaiThucHienKHCDSP_DaHoanThanh {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHCDSP_DaHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHCDSP_DangThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHCDSP_DangThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHNM_ChuaThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHNM_ChuaThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string iTrangThaiThucHienKHNM_DaHoanThanh {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHNM_DaHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHNM_DangThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHNM_DangThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHSC_ChuaThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHSC_ChuaThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string iTrangThaiThucHienKHSC_DaHoanThanh {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHSC_DaHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        public static string iTrangThaiThucHienKHSC_DangThucHien {
            get {
                return ResourceManager.GetString("iTrangThaiThucHienKHSC_DangThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa sử dụng.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_ChuaSuDung {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_ChuaSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang bảo hành.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DangBaoHanh {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DangBaoHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cho mượn.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DangChoMuon {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DangChoMuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sửa chữa.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DangSuaChua {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DangSuaChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DangSuDung {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thu hồi/thanh lý.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DaThuHoiThanhLy {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DaThuHoiThanhLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tiêu hủy.
        /// </summary>
        public static string TrangThaiTimKiemSanPham_DaTieuHuy {
            get {
                return ResourceManager.GetString("TrangThaiTimKiemSanPham_DaTieuHuy", resourceCulture);
            }
        }
    }
}
